# Generated by Django 5.2.15 on 2026-07-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_full_name_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ("pk",), "verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
